### ISSUE TITLE
issue when running the tool

### ISSUE THREAD

**Issue by BodaTomato** [Cyber-Dioxide/IP_Rover#2]
Traceback (most recent call last):                                                                                                                                                    File "/home/tim/IP_Rover/finder.py", line 26, in <module>                                                                                                                             program()                                                                                                                                                                         File "/home/tim/IP_Rover/finder.py", line 16, in program                                                                                                                              location = ipapi.location(ip)                                                                                                                                                     File "/usr/local/lib/python3.10/dist-packages/ipapi/ipapi.py", line 87, in location                                                                                                   raise RateLimited(data)                                                                                                                                                         ipapi.exceptions.RateLimited: {'error': True, 'reason': 'RateLimited', 'message': 'Visit https://ipapi.co/ratelimited/ for details'}

**Comment by Cyber-Dioxide** [comment]
> Traceback (most recent call last):                                                                                                                                                    File "/home/tim/IP_Rover/finder.py", line 26, in <module>                                                                                                                             program()                                                                                                                                                                         File "/home/tim/IP_Rover/finder.py", line 16, in program                                                                                                                              location = ipapi.location(ip)                                                                                                                                                     File "/usr/local/lib/python3.10/dist-packages/ipapi/ipapi.py", line 87, in location                                                                                                   raise RateLimited(data)                                                                                                                                                         ipapi.exceptions.RateLimited: {'error': True, 'reason': 'RateLimited', 'message': 'Visit https://ipapi.co/ratelimited/ for details'} 


From ipapi


For free plans (no authentication key)
If you were rate limited sooner than expected, the system may have detected suspicious activity from your IP block or region. Please message us. We'll be happy to resolve this for you swiftly.
If you've exceeded your lookup balance, please sign-up for a suitable plan with a higher limit.
